name: Make Release
on:
  push:
    tags: [ "v[0-9]*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake build-essential \
             curl debhelper-compat devscripts libtool libyaml-dev make \
             libusb-1.0-0-dev
        tools/install-libvna-deb
    - name: Build Debian Packages
      run: |
        ./bootstrap
        ./configure
        make -j8 deb
    - name: Build RPM Packages
      run: |
        podman run --rm -v "`pwd`:/n2pkvna" almalinux:8 \
            /n2pkvna/tools/make-rpm
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Assets
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: >
          ["deb/*.buildinfo",
           "deb/*.deb",
           "deb/*.dsc",
           "n2pkvna-*.tar.gz",
           "rpm/x86_64/*.rpm",
           "rpm/*.src.rpm"]
